"""
LangGraph node functions for the code-orchestration graph.

Node contract (LangGraph requirement):
  - Signature: (state: GraphState) -> dict
  - Return:    A *partial* dict containing only the keys this node changes.
               LangGraph merges it into the full state automatically.
  - Side-effects: DB writes, file writes, and subprocess calls are fine —
                  nodes are not required to be pure functions.

Design principles:
  - Nodes do NOT contain business logic. They delegate to existing classes
    (CodeAgent, TestAgent, DebuggerAgent, Runner, repositories).
  - ExecutionContext is reconstructed from GraphState inside nodes that need
    it, keeping the existing agents completely unchanged.
  - The DB session is opened and closed within the node that needs it.
    This avoids long-lived sessions crossing node boundaries.
"""

from __future__ import annotations

import uuid
import logging
from datetime import datetime
from pathlib import Path

from app.agents.coder import CodeAgent
from app.agents.tester import TestAgent
from app.agents.debugger import DebuggerAgent
from app.runner.runner import Runner
from app.sandbox.workspace_mgr import WorkspaceManager
from app.core.logger import get_logger
from app.schemas.execution_context import ExecutionContext

from app.db.session import SessionLocal
from app.repositories.execution_repository import ExecutionRepository
from app.repositories.iteration_repository import ExecutionIterationRepository

from app.orchestrator.graph.state import GraphState
from app.orchestrator.graph.edges import analyze_failure, MAX_TRIES

# Runner is stateless and model-independent — safe as a module singleton.
_runner = Runner()

def _update_job_meta(step_text: str):
    try:
        from rq import get_current_job
        job = get_current_job()
        if job:
            job.meta["stepText"] = step_text
            job.save_meta()
    except Exception:
        pass



def _rebuild_context(state: GraphState) -> tuple[ExecutionContext, Path]:
    """
    Reconstruct an ExecutionContext from GraphState.

    Called by any node that must pass a context object to an existing agent.
    WorkspaceManager is re-instantiated cheaply (it has no internal state
    beyond the base directory path).
    """
    workspace_path = Path(state["workspace_path"])
    workspace = WorkspaceManager()

    ctx = ExecutionContext(workspace=workspace, workspace_path=workspace_path)
    ctx.execution_id = state["execution_id"]
    ctx.version = state.get("version", 1)
    ctx.iteration = state.get("iteration", 0)
    ctx.status = state.get("status", "running")
    ctx.started_at = datetime.fromisoformat(state["started_at"])

    return ctx, workspace_path


# ── Node 1: initialize ────────────────────────────────────────────────────────

def node_initialize(state: GraphState) -> dict:
    """
    Create the workspace directory, insert the Execution DB row, and
    set up the execution-scoped logger.

    This is the only node that creates side-effects visible to the outside
    world before any LLM call is made, so it is intentionally kept minimal.
    """
    workspace = WorkspaceManager()
    workspace_path = workspace.create_workspace()

    started_at = datetime.utcnow()

    logger = get_logger("orchestrator.graph", workspace_path / "execution.log")
    logger.info(f"[initialize] workspace={workspace_path}")

    db = SessionLocal()
    try:
        repo = ExecutionRepository(db)
        user_id = state.get("user_id")
        if isinstance(user_id, str):
            import uuid
            try:
                user_id = uuid.UUID(user_id)
            except ValueError:
                pass
        execution = repo.create(
            requirement=state["requirement"],
            workspace_path=str(workspace_path),
            started_at=started_at,
            user_id=user_id,
        )
        # execution.id is a UUID auto-generated by the DB / model default
        execution_id = str(execution.id)
    finally:
        db.close()

    logger.info(f"[initialize] execution_id={execution_id}")

    return {
        "execution_id": execution_id,
        "user_id": state.get("user_id"),
        "workspace_path": str(workspace_path),
        "status": "running",
        "version": 1,
        "iteration": 0,
        "started_at": started_at.isoformat(),
        "last_error_type": None,
        "no_progress_count": 0,
        # runner output defaults (overwritten by node_run_tests)
        "passed": False,
        "stdout": "",
        "stderr": "",
        "exit_code": -1,
        "tries_used": 0,
    }


# ── Node 2: generate_code ─────────────────────────────────────────────────────

# Keywords that indicate a coding/programming request (fast local heuristic
# instead of burning an LLM roundtrip for classification).
_CODE_KEYWORDS = {
    "function", "class", "implement", "code", "program", "script", "algorithm",
    "api", "app", "application", "build", "create", "write", "develop", "fix",
    "debug", "refactor", "test", "solve", "parse", "sort", "search", "crud",
    "database", "server", "endpoint", "frontend", "backend", "cli", "bot",
    "scraper", "crawler", "library", "module", "package", "deploy", "docker",
    "python", "javascript", "typescript", "java", "html", "css", "react",
    "flask", "django", "fastapi", "node", "express", "sql", "rest", "graphql",
    "def ", "import ", "pip", "npm", "fibonacci", "linked list", "binary tree",
    "stack", "queue", "hash", "regex", "calculator", "game", "todo",
}


def _is_code_request(requirement: str) -> bool:
    """Fast keyword-based classification — no LLM call needed."""
    text = requirement.lower()
    return any(kw in text for kw in _CODE_KEYWORDS)


def node_generate_code(state: GraphState) -> dict:
    """
    Generate both solution.py AND test_solution.py in a single LLM call.

    Uses a fast keyword heuristic instead of an LLM classification call to
    determine if the requirement is code-related. If it is, uses the combined
    CODE_AND_TESTS_PROMPT so we get both files in one roundtrip.
    """
    ctx, _ = _rebuild_context(state)
    logger = get_logger("orchestrator.graph")
    logger.info(f"[generate_code] execution_id={state['execution_id']}")
    _update_job_meta("Generating code...")

    model = state.get("model")
    requirement = state["requirement"]

    # 1. Fast local classification (no LLM call)
    is_code = _is_code_request(requirement)
    logger.info(f"[generate_code] keyword classification: is_code={is_code}")

    if not is_code:
        logger.info("[generate_code] requirement is not for code, returning specific text.")
        specific_text = "I can only help with writing code. Please ask a coding-related question."

        ctx.workspace.write_file(ctx.workspace_path, "solution.py", specific_text)
        ctx.workspace.save_version(ctx.workspace_path, ctx.version, specific_text)
        return {
            "version": ctx.version,
            "iteration": 1,
            "is_code": False,
            "passed": True,
            "stdout": "Non-code requirement detected. Specific text returned.",
            "exit_code": 0,
        }

    # 2. Generate code AND tests in one LLM call
    from app.services.llm.factory import LLMFactory
    from app.services.llm.prompts import CODE_AND_TESTS_PROMPT

    llm = LLMFactory.create(model=model)
    prompt = CODE_AND_TESTS_PROMPT.format(requirement=requirement)
    _update_job_meta("Generating code & tests...")
    response = llm.generate(prompt)

    if not response or len(response.strip()) < 10:
        raise ValueError("LLM returned invalid code")

    # 3. Parse the combined response into solution + tests
    solution_code, test_code = _parse_combined_response(response.strip())

    # 4. Write solution
    ctx.workspace.write_file(ctx.workspace_path, "solution.py", solution_code)
    ctx.workspace.save_version(ctx.workspace_path, ctx.version, solution_code)

    # 5. Write tests (if we got them)
    if test_code:
        ctx.workspace.write_file(ctx.workspace_path, "test_solution.py", test_code)

    return {
        "version": ctx.version,
        "is_code": True,
        "tests_generated": bool(test_code),
    }


def _parse_combined_response(response: str) -> tuple[str, str]:
    """
    Split an LLM response that contains both solution and tests separated
    by '=== SOLUTION ===' and '=== TESTS ===' markers.

    Falls back gracefully: if markers are missing, treats the entire response
    as solution code and returns empty test code.
    """
    from app.services.llm.llm_service import clean_code

    sol_marker = "=== SOLUTION ==="
    test_marker = "=== TESTS ==="

    if sol_marker in response and test_marker in response:
        parts = response.split(test_marker, 1)
        solution_part = parts[0].split(sol_marker, 1)[-1].strip()
        test_part = parts[1].strip()
        return clean_code(solution_part), clean_code(test_part)

    # Fallback: no markers found — treat entire response as solution
    return clean_code(response), ""


# ── Node 3: generate_tests ────────────────────────────────────────────────────

def node_generate_tests(state: GraphState) -> dict:
    """
    Generate tests if they weren't already produced by node_generate_code.

    When CODE_AND_TESTS_PROMPT succeeds, tests are already written and this
    node is a no-op. Only falls back to a separate LLM call if tests are
    missing.
    """
    ctx, _ = _rebuild_context(state)
    logger = get_logger("orchestrator.graph")

    # Check if tests were already generated in the combined call
    if state.get("tests_generated", False):
        logger.info("[generate_tests] tests already generated — skipping")
        return {}

    # Fallback: generate tests separately
    logger.info(f"[generate_tests] execution_id={state['execution_id']} — fallback")
    _update_job_meta("Generating tests...")

    model = state.get("model")
    test_agent = TestAgent(model=model)
    test_agent.run(ctx)

    return {}



# ── Node 4: run_tests ─────────────────────────────────────────────────────────

def node_run_tests(state: GraphState) -> dict:
    """
    Execute pytest inside the workspace via Runner and capture the result.

    Increments ``iteration`` so the loop counter reflects the current attempt.
    Runner is left completely unchanged — it receives only workspace_path.
    """
    workspace_path = Path(state["workspace_path"])
    new_iteration = state.get("iteration", 0) + 1

    logger = get_logger("orchestrator.graph")
    logger.info(
        f"[run_tests] execution_id={state['execution_id']} "
        f"attempt={new_iteration}/{MAX_TRIES}"
    )
    _update_job_meta(f"Running tests (Attempt {new_iteration}/{MAX_TRIES})...")

    result = _runner.run(workspace_path)

    logger.info(
        f"[run_tests] passed={result.passed} "
        f"exit_code={result.exit_code}"
    )

    return {
        "iteration": new_iteration,
        "passed": result.passed,
        "stdout": result.stdout,
        "stderr": result.stderr,
        "exit_code": result.exit_code,
    }


# ── Node 5: save_iteration ────────────────────────────────────────────────────

def node_save_iteration(state: GraphState) -> dict:
    """
    Persist the current iteration result to the database.

    Intentionally a separate node (not merged into node_run_tests) so it can
    be independently retried, mocked in tests, or observed via checkpointing
    without re-running the subprocess.
    """
    workspace_path = Path(state["workspace_path"])
    workspace = WorkspaceManager()

    logger = get_logger("orchestrator.graph")
    logger.info(
        f"[save_iteration] execution_id={state['execution_id']} "
        f"iteration={state['iteration']} passed={state['passed']}"
    )

    iteration_code = workspace.read_file(workspace_path, "solution.py")

    db = SessionLocal()
    try:
        iter_repo = ExecutionIterationRepository(db)
        execution_id = state["execution_id"]
        if isinstance(execution_id, str):
            import uuid
            try:
                execution_id = uuid.UUID(execution_id)
            except ValueError:
                pass
        iter_repo.create(
            execution_id=execution_id,
            iteration_number=state["iteration"],
            generated_code=iteration_code,
            test_output=state.get("stdout", ""),
            passed=state.get("passed", False),
        )
    finally:
        db.close()

    return {}


# ── Node 6: analyze_progress ──────────────────────────────────────────────────

def node_analyze_progress(state: GraphState) -> dict:
    """
    Update the no-progress counter and last-error-type tracker.

    This node exists because LangGraph conditional edge functions cannot
    mutate state — they can only read it and return a routing key. Progress
    tracking requires state mutation, so it must live in a node that runs
    immediately before the conditional edge is evaluated.

    The routing logic in edges.route_after_analysis() reads the values written
    here to make its decision.
    """
    error_type = analyze_failure(
        state.get("stdout", ""),
        state.get("stderr", ""),
    )

    last = state.get("last_error_type")
    no_progress = state.get("no_progress_count", 0)

    if not state.get("passed", False):
        if error_type == last:
            no_progress += 1
        else:
            no_progress = 0

    logger = get_logger("orchestrator.graph")
    logger.info(
        f"[analyze_progress] error_type={error_type} "
        f"no_progress_count={no_progress}"
    )

    return {
        "last_error_type": error_type,
        "no_progress_count": no_progress,
    }


# ── Node 7: debug ─────────────────────────────────────────────────────────────

def node_debug(state: GraphState) -> dict:
    """
    Invoke DebuggerAgent to produce a fixed version of solution.py.

    DebuggerAgent increments context.version internally when it produces a
    meaningful change. We propagate that back to GraphState so version
    snapshots remain accurate across loop iterations.
    """
    ctx, _ = _rebuild_context(state)
    logger = get_logger("orchestrator.graph")
    logger.info(
        f"[debug] execution_id={state['execution_id']} "
        f"version_before={ctx.version}"
    )
    _update_job_meta("Self-healing and debugging...")

    model = state.get("model")
    debugger_agent = DebuggerAgent(model=model)
    debugger_agent.run(ctx, state.get("stdout", ""))

    logger.info(f"[debug] version_after={ctx.version}")

    # ctx.version may have been incremented by DebuggerAgent
    return {"version": ctx.version}


# ── Node 8: finalize ──────────────────────────────────────────────────────────

def node_finalize(state: GraphState) -> dict:
    """
    Determine final status, update the Execution DB row, and log completion.

    This is the terminal node — the graph transitions to END immediately after.
    It mirrors the "FINALIZE" block in the original orchestrator.
    """
    final_status = "success" if state.get("passed", False) else "failed"
    finished_at = datetime.utcnow()
    tries_used = state.get("iteration", 0)

    logger = get_logger("orchestrator.graph")
    logger.info(
        f"[finalize] execution_id={state['execution_id']} "
        f"status={final_status} tries_used={tries_used}"
    )

    db = SessionLocal()
    try:
        repo = ExecutionRepository(db)
        from app.db.models.execution import Execution
        execution_id = state["execution_id"]
        if isinstance(execution_id, str):
            import uuid
            try:
                execution_id = uuid.UUID(execution_id)
            except ValueError:
                pass
        execution = (
            db.query(Execution)
            .filter(Execution.id == execution_id)
            .first()
        )
        if execution:
            repo.update_status(
                execution=execution,
                status=final_status,
                tries_used=tries_used,
                finished_at=finished_at,
            )
    finally:
        db.close()

    return {
        "status": final_status,
        "tries_used": tries_used,
    }
